In [ ]:
!pip install dash

Collecting dash
  Downloading dash-3.0.4-py3-none-any.whl.metadata (10 kB)
Collecting Flask<3.1,>=1.0.4 (from dash)
  Downloading flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting Werkzeug<3.1 (from dash)
  Downloading werkzeug-3.0.6-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from dash) (5.24.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.11/dist-packages (from dash) (8.6.1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from dash) (4.13.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from dash) (2.32.3)
Collecting retrying (from dash)
  Downloading retrying-1.3.4-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.11/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from dash) (75.2.0)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in /usr/local/lib/python3.11/dist-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=5.0.0->dash) (24.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->dash) (2025.1.31)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from retrying->dash) (1.17.0)
Downloading dash-3.0.4-py3-none-any.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 76.6 MB/s eta 0:00:00
Downloading flask-3.0.3-py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 8.1 MB/s eta 0:00:00
Downloading werkzeug-3.0.6-py3-none-any.whl (227 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 17.5 MB/s eta 0:00:00
Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Installing collected packages: Werkzeug, retrying, Flask, dash
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 3.1.3
    Uninstalling Werkzeug-3.1.3:
      Successfully uninstalled Werkzeug-3.1.3
  Attempting uninstall: Flask
    Found existing installation: Flask 3.1.0
    Uninstalling Flask-3.1.0:
      Successfully uninstalled Flask-3.1.0
Successfully installed Flask-3.0.3 Werkzeug-3.0.6 dash-3.0.4 retrying-1.3.4

In [ ]:
!pip install dash_core_components

Collecting dash_core_components
  Downloading dash_core_components-2.0.0-py3-none-any.whl.metadata (2.9 kB)
Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Installing collected packages: dash_core_components
Successfully installed dash_core_components-2.0.0

In [ ]:
!pip install dash_html_components

Collecting dash_html_components
  Downloading dash_html_components-2.0.0-py3-none-any.whl.metadata (3.8 kB)
Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Installing collected packages: dash_html_components
Successfully installed dash_html_components-2.0.0

In [ ]:
#Passo 1 -> Lendo os dados e realizando o tratamento

import pandas as pd
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html

# Load the CSV file
df=pd.read_csv('/content/Summer_olympic_Medals.csv')
# Replace 'United States' with 'United States of America' in the 'Country_Name' column
df['Country_Name'] = df['Country_Name'].replace('United States', 'United States of America')

<ipython-input-7-0660128e2ce0>:7: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

In [ ]:
df

In [ ]:
#Passo 2: Plotando gráfico de Mapa

# Filtre os dados entre 1992 e 2020
df = df [( df['Year'] >= 1992) & ( df ['Year'] <= 2020)]

# Calcula o total de medalhas para cada país
df [ 'Total_Medals' ] = df [ 'Gold' ] + df [ 'Silver' ] + df [ 'Bronze' ]
df_country_medals = df.groupby('Country_Name')['Total_Medals'].sum().reset_index()

# Gera um mapa gráfico
map_fig = px.choropleth(df_country_medals,
                    locations= 'Country_Name' ,      # Coluna DataFrame com nomes de países
                    locationmode= 'country names' ,
                    color= 'Total_Medals' ,          # Coluna DataFrame com valores de cor
                    hover_name= 'Country_Name' ,     # Coluna DataFrame hover info
                    color_continuous_scale=px.colors.sequential.YlOrRd,   # Defina a escala de cores
                    title= 'Total de medalhas de 1992 a 2020' )   # Título do enredo
map_fig.show()

<ipython-input-8-a1f4169069a6>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df [ 'Total_Medals' ] = df [ 'Gold' ] + df [ 'Silver' ] + df [ 'Bronze' ]

In [ ]:
df

In [ ]:
#Passo 3 -> Plotando gráfico de área dos 10 paises com maior número de medalhas

# Crie um gráfico de área empilhado para os 10 principais países por contagem total de medalhas
top_countries = df_country_medals.groupby('Country_Name')['Total_Medals'].sum().nlargest(10).index
top_countries

Index(['United States of America', 'China', 'Russia', 'Germany',
       'Great Britain', 'Australia', 'France', 'Japan', 'Italy',
       'South Korea'],
      dtype='object', name='Country_Name')

In [ ]:
df_countries = df.groupby(['Country_Name', 'Year'])['Total_Medals'].sum().reset_index()
df_countries

    Country_Name  Year  Total_Medals
0    Afghanistan  2008             1
1    Afghanistan  2012             1
2        Algeria  1992             2
3        Algeria  1996             3
4        Algeria  2000             5
..           ...   ...           ...
644   Yugoslavia  1996             4
645   Yugoslavia  2000             3
646       Zambia  1996             1
647     Zimbabwe  2004             3
648     Zimbabwe  2008             4

[649 rows x 3 columns]

In [ ]:
df_top_10_countries = df_countries[df_countries['Country_Name'].isin(top_countries)]
df_top_10_countries

                 Country_Name  Year  Total_Medals
22                  Australia  1992            27
23                  Australia  1996            41
24                  Australia  2000            58
25                  Australia  2004            50
26                  Australia  2008            46
..                        ...   ...           ...
622  United States of America  2004           101
623  United States of America  2008           112
624  United States of America  2012           104
625  United States of America  2016           121
626  United States of America  2020           113

[78 rows x 3 columns]

In [ ]:
area_fig = px.area(df_top_10_countries,
                   x= "Year" ,
                   y= "Total_Medals",
                   color= "Country_Name",
                   title= 'Top 10 Países por contagem total de medalhas de 1992 a 2020' )

area_fig.show()

In [ ]:

# Crie um aplicativo Dash
app = dash.Dash(__name__)


# Defina o layout
app.layout = html.Div(children=[
    dcc.Graph(figure=map_fig),
    dcc. Graph(figure=area_fig)
])

# Execute o aplicativo
if __name__ == "__main__" :
    app.run( debug = False )  #com debug=True -> fica ativado o modo debug e exibindo as mensagens de erro

In [ ]:
#Passo 4 -> Plotando gráfico de Barra com os 10 paises com maior número de medalhas de ouro

# Crie um gráfico de área empilhado para os 10 principais países por contagem total de medalhas
df_top_countries_gold = df.groupby('Country_Name')['Gold'].sum().nlargest(10).reset_index()
df_top_countries_gold

In [ ]:
# Create a bar chart for the top 10 countries with most gold medals

bar_fig = px.bar(df_top_countries_gold, x='Country_Name', y='Gold', title='Top 10 Countries with Most Gold Medals from 1992 to 2020')
bar_fig.show()

In [ ]:
#Passo 5 -> Estilazando a tela com color_discrete_sequence = gold

bar_fig = px.bar(df_top_countries_gold, x='Country_Name', y='Gold', color_discrete_sequence=['gold'], title='Top 10 Countries with Most Gold Medals from 1992 to 2020')
bar_fig.show()

In [ ]:

# Create a Dash Application
app = dash.Dash(__name__)

# Define the layout
app.layout = html.Div([
    dcc.Graph(figure=map_fig, id='map'),
    html.Div([
        dcc.Graph(figure=area_fig, id='area-chart'),
        dcc.Graph(figure=bar_fig, id='bar-chart')
    ], style={'display': 'flex'})
])


# Execute o aplicativo
if __name__ == '__main__' :
    app.run_server( debug = False )  #com debug=True -> fica ativado o modo debug e exibindo as mensagens de erro

In [ ]:
#Passo 5 -> Estizando a tela com ajuste do mapa dentro do container div

# Create a Dash Application
app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Graph(figure=map_fig, id='map', style={'height': '50vh', 'width': '100%'}),
    html.Div([
        dcc.Graph(figure=area_fig, id='area-chart'),
        dcc.Graph(figure=bar_fig, id='bar-chart')
    ], style={'display': 'flex'})
])

# Execute o aplicativo
if __name__ == '__main__' :
    app.run_server( debug = False )  #com debug=True -> fica ativado o modo debug e exibindo as mensagens de erro